[tool.poetry]
name = "storytime"
version = "0.0.1-alpha.3"
description = "Storytime"
authors = ["Paul Everitt <pauleveritt@me.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/pauleveritt/storytime"
repository = "https://github.com/pauleveritt/storytime"
documentation = "https://storytime.readthedocs.io"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.11",
]

[tool.poetry.urls]
Changelog = "https://github.com/pauleveritt/storytime/releases"

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
hopscotch = "^0.3.1"
viewdom = "^0.6.4"
venusian = "^3.0.1"
tagged = "^0.0.2"
beautifulsoup4 = "^4.12.2"

[tool.poetry.dev-dependencies]
pytest = "^7.4.3"
coverage = { extras = ["toml"], version = "^5.4" }
safety = "^2.3.5"
mypy = "^1.7.0"
xdoctest = { extras = ["colors"], version = "^0.15.5" }
sphinx = "^7.2.6"
sphinx-autobuild = "^2021.3.14"
pre-commit = "^3.5.0"
flake8 = "^6.1.0"
black = "^22.1"
flake8-bandit = "^4.1.1"
flake8-bugbear = "^23.9.16"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.3.0"
pep8-naming = "^0.13.3"
darglint = "^1.8.1"
reorder-python-imports = "^3.12.0"
pre-commit-hooks = "^4.1.0"
sphinx-click = "^5.1.0"
Pygments = "^2.17.2"
nox = "^2023.4.22"
nox-poetry = "^1.0.3"
furo = "^2023.9.10"
myst-parser = "^2.0"

[tool.poetry.scripts]
storytime = "storytime.__main__:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["storytime"]

[tool.coverage.report]
show_missing = true
fail_under = 80

[tool.mypy]
strict = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[[tool.mypy.overrides]]
module = [
    "bs4",
]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
